### ISSUE TITLE
CircleCIのartifactの仕様が変わった？

### ISSUE THREAD

**Issue by igrep** [haskell-jp/haskell-jp-blog-artifact#1]
背景はわからないのですが、どうも今日CircleCIがビルドしたものから、artifactsのURLが変わってしまっているみたいです。

例えば[こちらのコメント](https://github.com/haskell-jp/blog/commit/5c647ffa01258c8e5fe9d2a2fb893bb03e881896#commitcomment-37308900)における
https://circleci.com/gh/haskell-jp/blog/792/artifacts/0/root/project/generated-site/index.html
は404を返しますが実際には
https://792-86001049-gh.circle-artifacts.com/0/generated-site/index.html
が正しいURLとなったようです。
恐らく `/root/project`の部分を削れば正しいパスになると思われます。

なんで急に変わったのかはわかりませんが...

**Comment by fumieval** [comment]
修正しデプロイしました。
